### PR TITLE
Use failure based error instead of error_chain.

### LINKED ISSUE #67: Consider switching to a error type which is `Sync`
Consider switching to a error type which is `Sync` (so that it can be turned into a `Failure` error).

`Fail` requires `Send`+`Sync`+`'static` but error chain errors are not `Sync` (due to the way they handle backtraces if I remember correctly).

### PR DESCRIPTION
**Pull request by rustonaut**
Fix #67

Now Error is `'statis + Send + Sync` before it
was not `Sync` which could cause problems.

### CODE REVIEW

**Comment by rustonaut** [comment]
Sorry for taking so long, a lot of work came my way and I somehow forgot that I didn't yet made a pull-request.

**Comment by rustonaut** [comment]
Also a Version bump (to 0.8) is still needed as the `Error` type changed.

**Comment by oli-obk** [comment]
Super! Thanks

**Comment by phil-opp** [comment]
@oli-obk Could you release a new version on crates.io that includes this PR?

**Pull request merged**
