### PR TITLE
Implement `Serialize` on everything

### PR DESCRIPTION
**Pull request by koute**

### CODE REVIEW

**Comment by oli-obk** [comment]
Can you supply a motivation and mention it in the readme, too?

**Comment by koute** [comment]
The motivation is mainly to support generating `--message-format=json` output in `cargo` subcommands just as `cargo` does. Some of the types in what `cargo --message-format=json` emits are exactly the same as the ones from `cargo metadata`.

How exactly would you like this mentioned in the README? Would this be fine?

> Also supports serialization to aid in implementing `--message-format=json`-like output generation in `cargo-*` subcommands, since some of the types in what `cargo --message-format=json` emits are exactly the same as the ones from `cargo metadata`.

**Comment by oli-obk** [comment]
Jup, that's perfect.

I just didn't know about that use case.

**Comment by koute** [comment]
README updated! Is that fine?

**Comment by oli-obk** [comment]
Great! thanks. I'll push a new minor version asap

**Comment by oli-obk** [comment]
Published as 0.4.1

**Pull request merged**
