### PR TITLE
Export ErrorKind

### PR DESCRIPTION
**Pull request by bjgill**
Needed to allow error chaining to work properly.

### CODE REVIEW

**Comment by bjgill** [comment]
Sorry - a rather silly omission on my part when switching to error chain.

**Comment by oli-obk** [comment]
Travis is unhappy with your changes without docs

**Comment by bjgill** [comment]
Unfortunately, due to https://github.com/rust-lang-nursery/error-chain/issues/63, I don't think I can add docs to the foreign links.

I think there are two possible solutions:

1. move the `error_chain!{..}` to an `errors` module, and mark that as `![allow(missing_docs)]`
2. remove the `foreign_links` section, and just use `.chain_err(|| "...")` instead

Thoughts? I think I prefer the second solution, as it seems like a more natural use of error-chain.

**Comment by oli-obk** [comment]
Sounds to me like the second solution is a breaking change.

**Comment by bjgill** [comment]
Ok - the first is easy enough to implement

**Comment by oli-obk** [comment]
I'll publish as soon as I get to a PC... which might not be before Friday next week though

**Pull request merged**
