### PR TITLE
add Package::is_publishable method

### PR DESCRIPTION
**Pull request by MarcoIeni**
I needed this tiny method in my code, so I opened a PR to add it here.
I already implemented this with a trait in my codebase, so feel free to close this PR if it is out of scope for this crate :)

### CODE REVIEW

**Comment by oli-obk** [comment]
Can you elaborate on your use case? Why/when would it be irrelevant which registry the crate can be published to?

**Comment by MarcoIeni** [comment]
In [release-plz](https://github.com/MarcoIeni/release-plz) I only update the publishable packages, because:
- it doesn't make sense to bump the version of packages which can't be published
- to determine the next version number, release-plz compares the local package with the one present in the cargo registry (it clones the published package and compares the two directories).

So I use this function to filter the workspace packages.

**Comment by oli-obk** [comment]
I've thought a bit about this and I think the function is too niche to be included here. It hides the fact that it may only be publishable on specific registries, which is fine for your use case, but I'd like to keep it explicit for everyone else.

**Comment by MarcoIeni** [comment]
Sure, no problem!

**Pull request closed without merging**
