### PR TITLE
Added Changelog file

### PR DESCRIPTION
**Pull request by morr0ne**
Adds a simple changelog file to keep track of the various changes.

### CODE REVIEW

**Comment by morr0ne** [comment]
Whoops. seems like a screwed up the branches and included #185 with the changes, Shouldn't be a problem if it gets merged first.

**Comment by morr0ne** [comment]
The changelog makes use of a github integrated feature which should auto-magically link up the version with the appropriate tag/release. I never tested this before, but it should be as easy as publishing a release with the same version

**Comment by morr0ne** [comment]
I fixed the accidental inclusion of #185 so now the only changes are the inclusion of the changelog file. It should be ready to merge without problems.

**Comment by oli-obk** [comment]
Please rebase the commit away instead of reverting it

**Comment by morr0ne** [comment]
That's the best I could do without access to my computer, I see know that was dumb. I'll fix it asap

**Pull request merged**
