### PR TITLE
Small changes to improve the overall crate quality

### PR DESCRIPTION
**Pull request by morr0ne**
see #175

### CODE REVIEW

**Comment by oli-obk** [comment]
Yea, I think a new breaking change is overdue, there's probably more things we'll want to do, too. I'll collect them for a while on master and release when we don't have anything left we'll want to break. 

Please unbump the edition and adjust the tests for the msrv

**Comment by morr0ne** [comment]
I think the best course of action is to eventually update the edition to avoid potential future problems. I reverted it back to the 2018 edition. There should be no conflicts now.

**Comment by morr0ne** [comment]
I believe it might be beneficial to also specify a rust-version in the manifest file (I believe the current msrv is 1.40.0). According to the [docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) the field would just be ignored on older rust version

**Comment by oli-obk** [comment]
I agree with both bumping the edition at some point and with adding the rust version to the manifest now

**Comment by oli-obk** [comment]
With the use of the matches macro we'll need to bump to 1.42 in this PR

**Comment by morr0ne** [comment]
I've been using rust for just 2 years so I never realized how relatively new the matches! macros is 😅. Should I revert it back? Using the macro is more ergonomic and readable but probably doesn't warrant a msrv bump.

**Comment by oli-obk** [comment]
I think the bump is definitely ok. It's 18 versions ago, so 27 months. I like having a bit over a year, even if the rust survey suggests that two versions is enough 🤣

**Comment by morr0ne** [comment]
Fair enough I guess lol. I actually never had to deal with msrv problems, I just use the latest nightly version that provides all the components. I'll update it as soon as I can. (Or possibly try from my phone 😬)

**Comment by morr0ne** [comment]
I managed to make the necessary edits from my phone. It should be good to go now.

**Pull request merged**
